// items.js — master item definitions (mirror of the server-side items table seed)
// IDs are stable — per CLAUDE.md Section 4.

// Tiering (after the Leather renumber, roadmap §35):
//   Tier 1 = Leather (IDs 19-22)  •  Tier 2 = Bronze  •  Tier 3 = Iron
// gold_value tracks tier (merchant pays the tier number, §19).
// IDs 1-18 are stable; Leather is appended as IDs 19-22.
const ITEMS = {
  1:  { id: 1,  name: 'Bronze Helmet',     type: 'armor',  tier: 2, slot_type: 'helmet',     accuracy_stat: 1,  strength_stat: 1, defense_stat: 1, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  2:  { id: 2,  name: 'Bronze Chestplate', type: 'armor',  tier: 2, slot_type: 'chestplate', accuracy_stat: 2,  strength_stat: 2, defense_stat: 2, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  3:  { id: 3,  name: 'Bronze Platelegs',  type: 'armor',  tier: 2, slot_type: 'platelegs',  accuracy_stat: 2,  strength_stat: 2, defense_stat: 2, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  4:  { id: 4,  name: 'Bronze Shield',     type: 'armor',  tier: 2, slot_type: 'shield',     accuracy_stat: 1,  strength_stat: 1, defense_stat: 1, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  5:  { id: 5,  name: 'Iron Helmet',       type: 'armor',  tier: 3, slot_type: 'helmet',     accuracy_stat: 1,  strength_stat: 1, defense_stat: 1, attack_req: 0,  defense_req: 20, gold_value: 3, stackable: 0 },
  6:  { id: 6,  name: 'Iron Chestplate',   type: 'armor',  tier: 3, slot_type: 'chestplate', accuracy_stat: 5,  strength_stat: 5, defense_stat: 5, attack_req: 0,  defense_req: 20, gold_value: 3, stackable: 0 },
  7:  { id: 7,  name: 'Iron Platelegs',    type: 'armor',  tier: 3, slot_type: 'platelegs',  accuracy_stat: 4,  strength_stat: 4, defense_stat: 4, attack_req: 0,  defense_req: 20, gold_value: 3, stackable: 0 },
  8:  { id: 8,  name: 'Iron Shield',       type: 'armor',  tier: 3, slot_type: 'shield',     accuracy_stat: 3,  strength_stat: 3, defense_stat: 3, attack_req: 0,  defense_req: 20, gold_value: 3, stackable: 0 },
  9:  { id: 9,  name: 'Bronze Kopesh',     type: 'weapon', tier: 2, slot_type: 'weapon',     accuracy_stat: 5,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  10: { id: 10, name: 'Bronze Stiletto',   type: 'weapon', tier: 2, slot_type: 'weapon',     accuracy_stat: 5,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  11: { id: 11, name: 'Bronze Battleaxe',  type: 'weapon', tier: 2, slot_type: 'weapon',     accuracy_stat: 5,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  12: { id: 12, name: 'Bronze Warhammer',  type: 'weapon', tier: 2, slot_type: 'weapon',     accuracy_stat: 5,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 2, stackable: 0 },
  13: { id: 13, name: 'Iron Kopesh',       type: 'weapon', tier: 3, slot_type: 'weapon',     accuracy_stat: 13, strength_stat: 1, defense_stat: 0, attack_req: 20, defense_req: 0,  gold_value: 3, stackable: 0 },
  14: { id: 14, name: 'Iron Stiletto',     type: 'weapon', tier: 3, slot_type: 'weapon',     accuracy_stat: 13, strength_stat: 1, defense_stat: 0, attack_req: 20, defense_req: 0,  gold_value: 3, stackable: 0 },
  15: { id: 15, name: 'Iron Battleaxe',    type: 'weapon', tier: 3, slot_type: 'weapon',     accuracy_stat: 13, strength_stat: 1, defense_stat: 0, attack_req: 20, defense_req: 0,  gold_value: 3, stackable: 0 },
  16: { id: 16, name: 'Iron Warhammer',    type: 'weapon', tier: 3, slot_type: 'weapon',     accuracy_stat: 13, strength_stat: 1, defense_stat: 0, attack_req: 20, defense_req: 0,  gold_value: 3, stackable: 0 },
  17: { id: 17, name: 'Cooked Chicken',    type: 'food',   tier: 0, slot_type: null,         accuracy_stat: 0,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 0, stackable: 1, heal: 5 },
  18: { id: 18, name: 'Gold',              type: 'gold',   tier: 0, slot_type: null,         accuracy_stat: 0,  strength_stat: 0, defense_stat: 0, attack_req: 0,  defense_req: 0,  gold_value: 0, stackable: 1 },
  // --- Tier 1: Leather (starter set, no requirements, stats just below Bronze) ---
  19: { id: 19, name: 'Leather Helmet',     type: 'armor', tier: 1, slot_type: 'helmet',     accuracy_stat: 1, strength_stat: 0, defense_stat: 1, attack_req: 0, defense_req: 0, gold_value: 1, stackable: 0 },
  20: { id: 20, name: 'Leather Jerkin',     type: 'armor', tier: 1, slot_type: 'chestplate', accuracy_stat: 1, strength_stat: 1, defense_stat: 1, attack_req: 0, defense_req: 0, gold_value: 1, stackable: 0 },
  21: { id: 21, name: 'Leather Platelegs',  type: 'armor', tier: 1, slot_type: 'platelegs',  accuracy_stat: 1, strength_stat: 1, defense_stat: 1, attack_req: 0, defense_req: 0, gold_value: 1, stackable: 0 },
  22: { id: 22, name: 'Leather Kite Shield',type: 'armor', tier: 1, slot_type: 'shield',     accuracy_stat: 1, strength_stat: 0, defense_stat: 1, attack_req: 0, defense_req: 0, gold_value: 1, stackable: 0 },
  // --- Tiers 4-11: Steel -> Eternal (spec gear ladder, placeholder visuals). IDs 23-86. ---
  23: { id: 23, name: 'Steel Helmet',         type: 'armor',  tier: 4, slot_type: 'helmet',    accuracy_stat: 3,  strength_stat: 3,  defense_stat: 3,  attack_req: 0,  defense_req: 30, gold_value: 4, stackable: 0 },
  24: { id: 24, name: 'Steel Chestplate',     type: 'armor',  tier: 4, slot_type: 'chestplate',accuracy_stat: 10, strength_stat: 10, defense_stat: 10, attack_req: 0,  defense_req: 30, gold_value: 4, stackable: 0 },
  25: { id: 25, name: 'Steel Platelegs',      type: 'armor',  tier: 4, slot_type: 'platelegs', accuracy_stat: 8,  strength_stat: 8,  defense_stat: 8,  attack_req: 0,  defense_req: 30, gold_value: 4, stackable: 0 },
  26: { id: 26, name: 'Steel Shield',         type: 'armor',  tier: 4, slot_type: 'shield',    accuracy_stat: 5,  strength_stat: 5,  defense_stat: 5,  attack_req: 0,  defense_req: 30, gold_value: 4, stackable: 0 },
  27: { id: 27, name: 'Steel Kopesh',         type: 'weapon', tier: 4, slot_type: 'weapon',    accuracy_stat: 25, strength_stat: 1,  defense_stat: 0, attack_req: 30,defense_req: 0,  gold_value: 4, stackable: 0 },
  28: { id: 28, name: 'Steel Stiletto',       type: 'weapon', tier: 4, slot_type: 'weapon',    accuracy_stat: 25, strength_stat: 1,  defense_stat: 0, attack_req: 30,defense_req: 0,  gold_value: 4, stackable: 0 },
  29: { id: 29, name: 'Steel Battleaxe',      type: 'weapon', tier: 4, slot_type: 'weapon',    accuracy_stat: 25, strength_stat: 1,  defense_stat: 0, attack_req: 30,defense_req: 0,  gold_value: 4, stackable: 0 },
  30: { id: 30, name: 'Steel Warhammer',      type: 'weapon', tier: 4, slot_type: 'weapon',    accuracy_stat: 25, strength_stat: 1,  defense_stat: 0, attack_req: 30,defense_req: 0,  gold_value: 4, stackable: 0 },
  31: { id: 31, name: 'Titanium Helmet',      type: 'armor',  tier: 5, slot_type: 'helmet',    accuracy_stat: 4,  strength_stat: 4,  defense_stat: 4,  attack_req: 0,  defense_req: 50, gold_value: 5, stackable: 0 },
  32: { id: 32, name: 'Titanium Chestplate',  type: 'armor',  tier: 5, slot_type: 'chestplate',accuracy_stat: 15, strength_stat: 15, defense_stat: 15, attack_req: 0,  defense_req: 50, gold_value: 5, stackable: 0 },
  33: { id: 33, name: 'Titanium Platelegs',   type: 'armor',  tier: 5, slot_type: 'platelegs', accuracy_stat: 11, strength_stat: 11, defense_stat: 11, attack_req: 0,  defense_req: 50, gold_value: 5, stackable: 0 },
  34: { id: 34, name: 'Titanium Shield',      type: 'armor',  tier: 5, slot_type: 'shield',    accuracy_stat: 8,  strength_stat: 8,  defense_stat: 8,  attack_req: 0,  defense_req: 50, gold_value: 5, stackable: 0 },
  35: { id: 35, name: 'Titanium Kopesh',      type: 'weapon', tier: 5, slot_type: 'weapon',    accuracy_stat: 38, strength_stat: 2,  defense_stat: 0, attack_req: 50,defense_req: 0,  gold_value: 5, stackable: 0 },
  36: { id: 36, name: 'Titanium Stiletto',    type: 'weapon', tier: 5, slot_type: 'weapon',    accuracy_stat: 38, strength_stat: 2,  defense_stat: 0, attack_req: 50,defense_req: 0,  gold_value: 5, stackable: 0 },
  37: { id: 37, name: 'Titanium Battleaxe',   type: 'weapon', tier: 5, slot_type: 'weapon',    accuracy_stat: 38, strength_stat: 2,  defense_stat: 0, attack_req: 50,defense_req: 0,  gold_value: 5, stackable: 0 },
  38: { id: 38, name: 'Titanium Warhammer',   type: 'weapon', tier: 5, slot_type: 'weapon',    accuracy_stat: 38, strength_stat: 2,  defense_stat: 0, attack_req: 50,defense_req: 0,  gold_value: 5, stackable: 0 },
  39: { id: 39, name: 'Tungsten Helmet',      type: 'armor',  tier: 6, slot_type: 'helmet',    accuracy_stat: 5,  strength_stat: 5,  defense_stat: 5,  attack_req: 0,  defense_req: 60, gold_value: 6, stackable: 0 },
  40: { id: 40, name: 'Tungsten Chestplate',  type: 'armor',  tier: 6, slot_type: 'chestplate',accuracy_stat: 21, strength_stat: 21, defense_stat: 21, attack_req: 0,  defense_req: 60, gold_value: 6, stackable: 0 },
  41: { id: 41, name: 'Tungsten Platelegs',   type: 'armor',  tier: 6, slot_type: 'platelegs', accuracy_stat: 16, strength_stat: 16, defense_stat: 16, attack_req: 0,  defense_req: 60, gold_value: 6, stackable: 0 },
  42: { id: 42, name: 'Tungsten Shield',      type: 'armor',  tier: 6, slot_type: 'shield',    accuracy_stat: 11, strength_stat: 11, defense_stat: 11, attack_req: 0,  defense_req: 60, gold_value: 6, stackable: 0 },
  43: { id: 43, name: 'Tungsten Kopesh',      type: 'weapon', tier: 6, slot_type: 'weapon',    accuracy_stat: 53, strength_stat: 1,  defense_stat: 0, attack_req: 60,defense_req: 0,  gold_value: 6, stackable: 0 },
  44: { id: 44, name: 'Tungsten Stiletto',    type: 'weapon', tier: 6, slot_type: 'weapon',    accuracy_stat: 53, strength_stat: 1,  defense_stat: 0, attack_req: 60,defense_req: 0,  gold_value: 6, stackable: 0 },
  45: { id: 45, name: 'Tungsten Battleaxe',   type: 'weapon', tier: 6, slot_type: 'weapon',    accuracy_stat: 53, strength_stat: 1,  defense_stat: 0, attack_req: 60,defense_req: 0,  gold_value: 6, stackable: 0 },
  46: { id: 46, name: 'Tungsten Warhammer',   type: 'weapon', tier: 6, slot_type: 'weapon',    accuracy_stat: 53, strength_stat: 1,  defense_stat: 0, attack_req: 60,defense_req: 0,  gold_value: 6, stackable: 0 },
  47: { id: 47, name: 'Obsidian Helmet',      type: 'armor',  tier: 7, slot_type: 'helmet',    accuracy_stat: 7,  strength_stat: 7,  defense_stat: 7,  attack_req: 0,  defense_req: 70, gold_value: 7, stackable: 0 },
  48: { id: 48, name: 'Obsidian Chestplate',  type: 'armor',  tier: 7, slot_type: 'chestplate',accuracy_stat: 28, strength_stat: 28, defense_stat: 28, attack_req: 0,  defense_req: 70, gold_value: 7, stackable: 0 },
  49: { id: 49, name: 'Obsidian Platelegs',   type: 'armor',  tier: 7, slot_type: 'platelegs', accuracy_stat: 21, strength_stat: 21, defense_stat: 21, attack_req: 0,  defense_req: 70, gold_value: 7, stackable: 0 },
  50: { id: 50, name: 'Obsidian Shield',      type: 'armor',  tier: 7, slot_type: 'shield',    accuracy_stat: 14, strength_stat: 14, defense_stat: 14, attack_req: 0,  defense_req: 70, gold_value: 7, stackable: 0 },
  51: { id: 51, name: 'Obsidian Kopesh',      type: 'weapon', tier: 7, slot_type: 'weapon',    accuracy_stat: 70, strength_stat: 2,  defense_stat: 0, attack_req: 70,defense_req: 0,  gold_value: 7, stackable: 0 },
  52: { id: 52, name: 'Obsidian Stiletto',    type: 'weapon', tier: 7, slot_type: 'weapon',    accuracy_stat: 70, strength_stat: 2,  defense_stat: 0, attack_req: 70,defense_req: 0,  gold_value: 7, stackable: 0 },
  53: { id: 53, name: 'Obsidian Battleaxe',   type: 'weapon', tier: 7, slot_type: 'weapon',    accuracy_stat: 70, strength_stat: 2,  defense_stat: 0, attack_req: 70,defense_req: 0,  gold_value: 7, stackable: 0 },
  54: { id: 54, name: 'Obsidian Warhammer',   type: 'weapon', tier: 7, slot_type: 'weapon',    accuracy_stat: 70, strength_stat: 2,  defense_stat: 0, attack_req: 70,defense_req: 0,  gold_value: 7, stackable: 0 },
  55: { id: 55, name: 'Dragonite Helmet',     type: 'armor',  tier: 8, slot_type: 'helmet',    accuracy_stat: 9,  strength_stat: 9,  defense_stat: 9,  attack_req: 0,  defense_req: 80, gold_value: 8, stackable: 0 },
  56: { id: 56, name: 'Dragonite Chestplate', type: 'armor',  tier: 8, slot_type: 'chestplate',accuracy_stat: 35, strength_stat: 35, defense_stat: 35, attack_req: 0,  defense_req: 80, gold_value: 8, stackable: 0 },
  57: { id: 57, name: 'Dragonite Platelegs',  type: 'armor',  tier: 8, slot_type: 'platelegs', accuracy_stat: 26, strength_stat: 26, defense_stat: 26, attack_req: 0,  defense_req: 80, gold_value: 8, stackable: 0 },
  58: { id: 58, name: 'Dragonite Shield',     type: 'armor',  tier: 8, slot_type: 'shield',    accuracy_stat: 18, strength_stat: 18, defense_stat: 18, attack_req: 0,  defense_req: 80, gold_value: 8, stackable: 0 },
  59: { id: 59, name: 'Dragonite Kopesh',     type: 'weapon', tier: 8, slot_type: 'weapon',    accuracy_stat: 88, strength_stat: 2,  defense_stat: 0, attack_req: 80,defense_req: 0,  gold_value: 8, stackable: 0 },
  60: { id: 60, name: 'Dragonite Stiletto',   type: 'weapon', tier: 8, slot_type: 'weapon',    accuracy_stat: 88, strength_stat: 2,  defense_stat: 0, attack_req: 80,defense_req: 0,  gold_value: 8, stackable: 0 },
  61: { id: 61, name: 'Dragonite Battleaxe',  type: 'weapon', tier: 8, slot_type: 'weapon',    accuracy_stat: 88, strength_stat: 2,  defense_stat: 0, attack_req: 80,defense_req: 0,  gold_value: 8, stackable: 0 },
  62: { id: 62, name: 'Dragonite Warhammer',  type: 'weapon', tier: 8, slot_type: 'weapon',    accuracy_stat: 88, strength_stat: 2,  defense_stat: 0, attack_req: 80,defense_req: 0,  gold_value: 8, stackable: 0 },
  63: { id: 63, name: 'Celestial Helmet',     type: 'armor',  tier: 9, slot_type: 'helmet',    accuracy_stat: 11, strength_stat: 11, defense_stat: 11, attack_req: 0,  defense_req: 85, gold_value: 9, stackable: 0 },
  64: { id: 64, name: 'Celestial Chestplate', type: 'armor',  tier: 9, slot_type: 'chestplate',accuracy_stat: 43, strength_stat: 43, defense_stat: 43, attack_req: 0,  defense_req: 85, gold_value: 9, stackable: 0 },
  65: { id: 65, name: 'Celestial Platelegs',  type: 'armor',  tier: 9, slot_type: 'platelegs', accuracy_stat: 32, strength_stat: 32, defense_stat: 32, attack_req: 0,  defense_req: 85, gold_value: 9, stackable: 0 },
  66: { id: 66, name: 'Celestial Shield',     type: 'armor',  tier: 9, slot_type: 'shield',    accuracy_stat: 21, strength_stat: 21, defense_stat: 21, attack_req: 0,  defense_req: 85, gold_value: 9, stackable: 0 },
  67: { id: 67, name: 'Celestial Kopesh',     type: 'weapon', tier: 9, slot_type: 'weapon',    accuracy_stat: 107,strength_stat: 3,  defense_stat: 0, attack_req: 85,defense_req: 0,  gold_value: 9, stackable: 0 },
  68: { id: 68, name: 'Celestial Stiletto',   type: 'weapon', tier: 9, slot_type: 'weapon',    accuracy_stat: 107,strength_stat: 3,  defense_stat: 0, attack_req: 85,defense_req: 0,  gold_value: 9, stackable: 0 },
  69: { id: 69, name: 'Celestial Battleaxe',  type: 'weapon', tier: 9, slot_type: 'weapon',    accuracy_stat: 107,strength_stat: 3,  defense_stat: 0, attack_req: 85,defense_req: 0,  gold_value: 9, stackable: 0 },
  70: { id: 70, name: 'Celestial Warhammer',  type: 'weapon', tier: 9, slot_type: 'weapon',    accuracy_stat: 107,strength_stat: 3,  defense_stat: 0, attack_req: 85,defense_req: 0,  gold_value: 9, stackable: 0 },
  71: { id: 71, name: 'Void Helmet',          type: 'armor',  tier: 10,slot_type: 'helmet',    accuracy_stat: 13, strength_stat: 13, defense_stat: 13, attack_req: 0,  defense_req: 90, gold_value: 10,stackable: 0 },
  72: { id: 72, name: 'Void Chestplate',      type: 'armor',  tier: 10,slot_type: 'chestplate',accuracy_stat: 51, strength_stat: 51, defense_stat: 51, attack_req: 0,  defense_req: 90, gold_value: 10,stackable: 0 },
  73: { id: 73, name: 'Void Platelegs',       type: 'armor',  tier: 10,slot_type: 'platelegs', accuracy_stat: 38, strength_stat: 38, defense_stat: 38, attack_req: 0,  defense_req: 90, gold_value: 10,stackable: 0 },
  74: { id: 74, name: 'Void Shield',          type: 'armor',  tier: 10,slot_type: 'shield',    accuracy_stat: 26, strength_stat: 26, defense_stat: 26, attack_req: 0,  defense_req: 90, gold_value: 10,stackable: 0 },
  75: { id: 75, name: 'Void Kopesh',          type: 'weapon', tier: 10,slot_type: 'weapon',    accuracy_stat: 128,strength_stat: 4,  defense_stat: 0, attack_req: 90,defense_req: 0,  gold_value: 10,stackable: 0 },
  76: { id: 76, name: 'Void Stiletto',        type: 'weapon', tier: 10,slot_type: 'weapon',    accuracy_stat: 128,strength_stat: 4,  defense_stat: 0, attack_req: 90,defense_req: 0,  gold_value: 10,stackable: 0 },
  77: { id: 77, name: 'Void Battleaxe',       type: 'weapon', tier: 10,slot_type: 'weapon',    accuracy_stat: 128,strength_stat: 4,  defense_stat: 0, attack_req: 90,defense_req: 0,  gold_value: 10,stackable: 0 },
  78: { id: 78, name: 'Void Warhammer',       type: 'weapon', tier: 10,slot_type: 'weapon',    accuracy_stat: 128,strength_stat: 4,  defense_stat: 0, attack_req: 90,defense_req: 0,  gold_value: 10,stackable: 0 },
  79: { id: 79, name: 'Eternal Helmet',       type: 'armor',  tier: 11,slot_type: 'helmet',    accuracy_stat: 15, strength_stat: 15, defense_stat: 15, attack_req: 0,  defense_req: 100,gold_value: 11,stackable: 0 },
  80: { id: 80, name: 'Eternal Chestplate',   type: 'armor',  tier: 11,slot_type: 'chestplate',accuracy_stat: 60, strength_stat: 60, defense_stat: 60, attack_req: 0,  defense_req: 100,gold_value: 11,stackable: 0 },
  81: { id: 81, name: 'Eternal Platelegs',    type: 'armor',  tier: 11,slot_type: 'platelegs', accuracy_stat: 45, strength_stat: 45, defense_stat: 45, attack_req: 0,  defense_req: 100,gold_value: 11,stackable: 0 },
  82: { id: 82, name: 'Eternal Shield',       type: 'armor',  tier: 11,slot_type: 'shield',    accuracy_stat: 30, strength_stat: 30, defense_stat: 30, attack_req: 0,  defense_req: 100,gold_value: 11,stackable: 0 },
  83: { id: 83, name: 'Eternal Kopesh',       type: 'weapon', tier: 11,slot_type: 'weapon',    accuracy_stat: 150,strength_stat: 5,  defense_stat: 0, attack_req: 100,defense_req: 0,  gold_value: 11,stackable: 0 },
  84: { id: 84, name: 'Eternal Stiletto',     type: 'weapon', tier: 11,slot_type: 'weapon',    accuracy_stat: 150,strength_stat: 5,  defense_stat: 0, attack_req: 100,defense_req: 0,  gold_value: 11,stackable: 0 },
  85: { id: 85, name: 'Eternal Battleaxe',    type: 'weapon', tier: 11,slot_type: 'weapon',    accuracy_stat: 150,strength_stat: 5,  defense_stat: 0, attack_req: 100,defense_req: 0,  gold_value: 11,stackable: 0 },
  86: { id: 86, name: 'Eternal Warhammer',    type: 'weapon', tier: 11,slot_type: 'weapon',    accuracy_stat: 150,strength_stat: 5,  defense_stat: 0, attack_req: 100,defense_req: 0,  gold_value: 11,stackable: 0 },
};
